/**
 * Generates the printable/greppable study lists under docs/hsk/.
 * Regenerate with `pnpm data:md` after any content batch — the diff shows
 * exactly what was filled in.
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { levelLabel } from "../app/lib/levels.ts";
import type { Hanzi, Level, Lexeme, Radical, Relation, Topic, Word } from "../app/lib/types.ts";
import { RELATION_UI_LABEL } from "../app/lib/lexical.ts";

const LEVELS: Level[] = [1, 2, 3, 4, 5, 6, 7];
const STATUS = { reviewed: "✅ reviewed", drafted: "📝 drafted", stub: "⬜ stub" } as const;

const esc = (s: string) => s.replace(/\|/g, "\\|");
const trunc = (s: string, n: number) => (s.length > n ? `${s.slice(0, n - 1)}…` : s);
const status = (a: { status: keyof typeof STATUS } | null) => STATUS[a?.status ?? "stub"];

function etymologyLabel(h: Hanzi): string {
  const e = h.etymology;
  if (!e) return "—";
  if (e.type !== "pictophonetic") return e.type;
  if (!e.phonetic) return "pictophonetic";
  return e.phoneticVisible === false
    ? `pictophonetic (声 ${e.phonetic}, lost)`
    : `pictophonetic (声 ${e.phonetic})`;
}

async function main() {
  const hanzi: Hanzi[] = JSON.parse(await readFile("app/data/generated/hanzi.json", "utf8"));
  const words: Word[] = JSON.parse(await readFile("app/data/generated/words.json", "utf8"));
  const radicals: Radical[] = JSON.parse(await readFile("app/data/generated/radicals.json", "utf8"));
  const topics: Topic[] = JSON.parse(await readFile("app/data/generated/topics.json", "utf8"));
  const relations: Relation[] = JSON.parse(
    await readFile("app/data/generated/relations.json", "utf8"),
  );
  const lexemes: Lexeme[] = JSON.parse(await readFile("app/data/generated/lexemes.json", "utf8"));
  const candidates: { reason: string; forms: string[]; kind: string; textbookPercentile: number | null }[] =
    JSON.parse(await readFile("app/data/generated/relation-candidates.json", "utf8"));

  for (const level of LEVELS) {
    const dir = `docs/hsk/level-${level}`;
    await mkdir(dir, { recursive: true });

    const hs = hanzi.filter((h) => h.level === level);
    const ws = words.filter((w) => !w.extra && w.level === level);
    const chars = new Set(hs.map((h) => h.char));
    const rs = radicals
      .map((r) => ({ ...r, hanzi: r.hanzi.filter((c) => chars.has(c)) }))
      .filter((r) => r.hanzi.length > 0);

    // ------------------------------------------------------------- hanzi.md
    const h: string[] = [
      `# HSK 3.0 Level ${levelLabel(level)} — Hanzi (${hs.length})`,
      "",
      `Grouped by radical, radicals ordered by stroke count. Generated by \`pnpm data:md\` — do not edit.`,
      "",
      `**Coverage:** ${hs.filter((x) => x.authored).length} of ${hs.length} documented · ` +
        `${hs.filter((x) => !x.etymology).length} have no upstream etymology and need manual research.`,
      "",
    ];
    for (const r of rs) {
      const alt = r.variants.filter((v) => v !== r.display);
      h.push(
        `## ${r.display} — ${r.gloss} · ${r.strokes} stroke${r.strokes > 1 ? "s" : ""} · ` +
          `Kangxi #${r.number} ${r.canonical}${alt.length ? ` (also ${alt.join(" ")})` : ""} · ` +
          `${r.hanzi.length} characters`,
        "",
        "| Hanzi | Pinyin | Meaning | Decomposition | Formation | Status |",
        "|---|---|---|---|---|---|",
      );
      for (const c of r.hanzi) {
        const x = hs.find((y) => y.char === c)!;
        h.push(
          `| ${x.char} | ${esc(x.pinyin.join(", "))} | ${esc(trunc(x.meanings.join("; "), 44))} ` +
            `| ${x.decomposition === "？" ? "—" : x.decomposition} | ${etymologyLabel(x)} | ${status(x.authored)} |`,
        );
      }
      h.push("");
    }
    await writeFile(`${dir}/hanzi.md`, h.join("\n"));

    // ------------------------------------------------------------- words.md
    const w: string[] = [
      `# HSK 3.0 Level ${levelLabel(level)} — Words (${ws.length})`,
      "",
      "Multi-character words introduced at this level. `Literal` and `Why` are filled in from",
      "`content/words/*.md`; blanks are the research backlog. Generated by `pnpm data:md`.",
      "",
      `**Coverage:** ${ws.filter((x) => x.authored).length} of ${ws.length} documented.`,
      "",
      "| Word | Pinyin | Meaning | Literal | Formation | Transparency | Status |",
      "|---|---|---|---|---|---|---|",
    ];
    for (const x of [...ws].sort((a, b) => (b.frequency ?? 0) - (a.frequency ?? 0))) {
      const a = x.authored;
      w.push(
        `| ${x.word} | ${esc(x.pinyin)} | ${esc(trunc(x.meanings.join("; "), 40))} ` +
          `| ${a ? esc(a.literal) : ""} | ${a?.formation ?? ""} | ${a?.transparency ?? ""} | ${status(a)} |`,
      );
    }
    await writeFile(`${dir}/words.md`, w.join("\n"));

    // ---------------------------------------------------------- radicals.md
    const r: string[] = [
      `# HSK 3.0 Level ${levelLabel(level)} — Radicals (${rs.length})`,
      "",
      "Every radical appearing in this level's characters, by stroke count.",
      "Generated by `pnpm data:md`.",
      "",
      "| Radical | Kangxi | Gloss | Strokes | Characters at this level |",
      "|---|---|---|---|---|",
    ];
    for (const x of rs) {
      const alt = x.variants.filter((v) => v !== x.display);
      r.push(
        `| ${x.display} | #${x.number} ${x.canonical}${alt.length ? ` (also ${alt.join(" ")})` : ""} ` +
          `| ${esc(x.gloss)} | ${x.strokes} | ${x.hanzi.join(" ")} |`,
      );
    }
    await writeFile(`${dir}/radicals.md`, r.join("\n"));

    // ---------------------------------------------------------- topics.md
    const wordSet = new Set(ws.map((w) => w.word));
    const ts = topics.map((t) => ({
      ...t,
      hanzi: t.hanzi.filter((c) => chars.has(c)),
      words: t.words.filter((w) => wordSet.has(w)),
    }));
    const taggedEntries =
      hs.filter((h) => h.topics.length > 0).length + ws.filter((w) => w.topics.length > 0).length;
    const totalEntries = hs.length + ws.length;

    const t: string[] = [
      `# HSK 3.0 Level ${levelLabel(level)} — Topics (${ts.filter((x) => x.hanzi.length + x.words.length > 0).length} of ${ts.length} in use)`,
      "",
      "Themes an entry belongs to. An entry may carry zero, one or several, so the",
      "counts below sum to more than the number of entries. Generated by `pnpm data:md`.",
      "",
      `**Coverage:** ${taggedEntries} of ${totalEntries} entries tagged · ` +
        `${totalEntries - taggedEntries} untagged.`,
      "",
      "| Topic | Hanzi | Words | Total | Members |",
      "|---|---|---|---|---|",
    ];
    for (const x of ts) {
      const total = x.hanzi.length + x.words.length;
      t.push(
        `| ${esc(x.label)} | ${x.hanzi.length} | ${x.words.length} | ${total} ` +
          `| ${total === 0 ? "—" : [...x.hanzi, ...x.words].join(" ")} |`,
      );
    }
    await writeFile(`${dir}/topics.md`, t.join("\n"));

    // ---------------------------------------------------------- relations.md
    const levelForms = new Set([...chars, ...ws.map((w) => w.word)]);
    const rels = relations.filter((r) => r.members.some((m) => levelForms.has(m.form)));
    const relatedWords = ws.filter((w) => w.relationIds.length > 0);
    const usageWords = ws.filter((w) => w.authored?.usage);
    const charLinked = ws.filter((w) => (w.authored?.chars.length ?? 0) > 0);
    const levelCandidates = candidates.filter((c) =>
      c.forms.some((f) => ws.some((w) => w.word === f)),
    );
    const relMd: string[] = [
      `# HSK 3.0 Level ${levelLabel(level)} — Relations (${rels.length})`,
      "",
      "Sense-specific synonym, antonym, and real-life-alternative sets that include a",
      "hanzi or word from this level. Generated by `pnpm data:md` — do not edit.",
      "",
      `**Coverage:** ${relatedWords.length} of ${ws.length} words in a relation · ` +
        `${usageWords.length} with a usage profile · ${charLinked.length} with character links.`,
      "",
      `Lexemes in the catalogue (any level): ${lexemes.length}.`,
      "",
      "| Relation | Kind | UI label | Members | Status |",
      "|---|---|---|---|---|",
    ];
    for (const r of rels) {
      relMd.push(
        `| ${esc(r.id)} | ${r.kind} | ${esc(RELATION_UI_LABEL[r.kind])} ` +
          `| ${r.members.map((m) => m.form).join(" ")} | ${status(r)} |`,
      );
    }
    relMd.push(
      "",
      "## Candidate backlog",
      "",
      "Generated from authored notes, formation, opacity, and textbook frequency.",
      "Not learner-facing until reviewed into `content/relations/` or `chars:`.",
      "",
      "| Forms | Kind | Percentile | Reason |",
      "|---|---|---|---|",
    );
    for (const c of levelCandidates.slice(0, 40)) {
      relMd.push(
        `| ${c.forms.join(" ")} | ${c.kind} | ${c.textbookPercentile ?? "—"} | ${esc(c.reason)} |`,
      );
    }
    if (levelCandidates.length === 0) relMd.push("| — | — | — | — |");
    relMd.push("");
    await writeFile(`${dir}/relations.md`, relMd.join("\n"));

    console.log(
      `docs/hsk/level-${level}/ — ${hs.length} hanzi · ${ws.length} words · ` +
        `${rs.length} radicals · ${taggedEntries}/${totalEntries} tagged · ${rels.length} relations`,
    );
  }

  const extra = words.filter((w) => w.extra);
  extra.sort((a, b) => a.word.localeCompare(b.word, "zh"));
  await mkdir("docs/extra", { recursive: true });
  const extraMd: string[] = [
    `# Extra — Countries and languages (${extra.length})`,
    "",
    "Supplement vocabulary that is not on the HSK 3.0 wordlist. Characters are",
    "already in the HSK hanzi set. Generated by `pnpm data:md` — do not edit.",
    "",
    `**Coverage:** ${extra.filter((x) => x.authored).length} of ${extra.length} documented.`,
    "",
    "| Word | Pinyin | Meaning | Literal | Formation | Transparency | Status |",
    "|---|---|---|---|---|---|---|",
  ];
  for (const x of extra) {
    const a = x.authored;
    extraMd.push(
      `| ${x.word} | ${esc(x.pinyin)} | ${esc(trunc(x.meanings.join("; "), 40))} ` +
        `| ${a ? esc(a.literal) : ""} | ${a?.formation ?? ""} | ${a?.transparency ?? ""} | ${status(a)} |`,
    );
  }
  extraMd.push("");
  await writeFile("docs/extra/words.md", extraMd.join("\n"));
  console.log(`docs/extra/words.md — ${extra.length} words`);
}

main();
